### ISSUE TITLE
update tlc sxl 1.1

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#23]
a 1.1 schema has been added, but not all spec changes are yet reflected in the schema

the sxl changelog is at:
https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/blob/master/ChangeLog.md

- [x] Designated command/status for priority rsmp-nordic/rsmp_sxl_traffic_lights#129. Add a specific command and status for requesting priority for designated - [ ] vehicles
- [x] S0091, S0092: "Operator logged in" updated rsmp-nordic/rsmp_sxl_traffic_lights#94. User name removed and login levels updated
- [x] A0005/A0007. Updated definitions rsmp-nordic/rsmp_sxl_traffic_lights#77
- [x] A0005 is used for communication error in coordination mode
- [x] A0007 is used for communication error with supervision system and NTP
- [x] Source of status changes rsmp-nordic/rsmp_sxl_traffic_lights#67. Ability to se the reason for switching status, e.g. source of plan change, dark mode, etc.
- [x] Coordination local/centralized rsmp-nordic/rsmp_sxl_traffic_lights#83. Ability to see if TLC is using local or centralized coordination
- [x] Add serious detector hardware and logic errors rsmp-nordic/rsmp_sxl_traffic_lights#108. Only low priority detector errors were defined. There is a need to be able to use detector error with a higher priority (serious error).
- [x] Timeout for dynamic bands. rsmp-nordic/rsmp_sxl_traffic_lights#95 and rsmp-nordic/rsmp_sxl_traffic_lights#96
- [x] Time until a designated time plan is entered due to lost connection with the supervisor
- [x] M0019 and M0005. True/False mixed up. rsmp-nordic/rsmp_sxl_traffic_lights#121 and rsmp-nordic/rsmp_sxl_traffic_lights#144
- [x] Both M0019 (force input) and M0005 (emergency route) had typos where True and False were mixed up in the description.
- [x] M0013: Add "All read" as possible option for Police Key rsmp-nordic/rsmp_sxl_traffic_lights#119
- [x] Use only JSON data types. Replace "long" with "integer" rsmp-nordic/rsmp_sxl_traffic_lights#133
- [x] S0001: Use '-' if there are gaps in the numbering rsmp-nordic/rsmp_sxl_traffic_lights#125
- [x] S0096, M0104, S0204, S0201, S0202: Define min, max correctly when using integers and long rsmp-nordic/rsmp_sxl_traffic_lights#131
- [x] A0008: Add list (1-255) instead of "designation" (time plan) rsmp-nordic/rsmp_sxl_traffic_lights#130
- [x] M0013: Fix error in example and description rsmp-nordic/rsmp_sxl_traffic_lights#134
- [x] Signal group status: Ascii character after each definition rsmp-nordic/rsmp_sxl_traffic_lights#103
- [x] S0011: Yellow flash. Clarification in description rsmp-nordic/rsmp_sxl_traffic_lights#112
- [x] M0019: Typo in example for "Force Input" rsmp-nordic/rsmp_sxl_traffic_lights#136
- [x] Aggregated Status, functionalPosition and functionalState (fS and fP) is unused rsmp-nordic/rsmp_sxl_traffic_lights#90
- [x] Definition of max. minimum green rsmp-nordic/rsmp_sxl_traffic_lights#102
- [x] Clarify that a number of statuses uses comma separated lists of intersections rsmp-nordic/rsmp_sxl_traffic_lights#122
- [x] Clarify meaning of "cycle counter" and "base cycle counter" rsmp-nordic/rsmp_sxl_traffic_lights#118

**Comment by emiltin** [comment]
test rsmp_nordic/rsmp_sxl_traffic_lights#118
